
FIND_PATH(SQLITE3_INCLUDE_DIR sqlite3.h /usr/local/include/sqlite3)
FIND_LIBRARY(SQLITE3_LIBRARY NAMES sqlite3 sqlite3d PATH /usr/local/lib)

IF(SQLITE3_INCLUDE_DIR AND SQLITE3_LIBRARY)
  SET(SQLITE3_FOUND true)
ENDIF(SQLITE3_INCLUDE_DIR AND SQLITE3_LIBRARY)

IF(SQLITE3_FOUND)
  IF(NOT SQLITE3_FIND_QUIETLY)
    MESSAGE(STATUS "Found SQLite3: ${SQLITE3_INCLUDE_DIR} ${SQLITE3_LIBRARY}")
  ENDIF(NOT HELLO_FIND_QUIETLY)
ELSE(SQLITE3_FOUND)
  IF(SQLITE3_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find sqlite3 library")
  ENDIF(SQLITE3_FIND_REQUIRED)
ENDIF(SQLITE3_FOUND)
